/** Official BIOPOWER brand / NAP constants — single source of truth (Phase 4) */
module.exports = {
  years: '17+',
  installations: '12,898+',
  rating: '4.9/5',
  reviewCount: '5000',
  founded: '2006',
  capacityRange: '1 kg/day to 100 metric tons/day',
  phone: '+91 73381 29464',
  phoneTel: '+917338129464',
  email: 'info@biopower.co.in',
  ga4: 'G-KT48H7F23D',
  site: 'https://biopower.co.in',
  orgName: 'BPG Renewables Pvt Ltd',
  brand: 'BIOPOWER',
  companyDisplay: 'BIOPOWER (BPG Renewables Pvt Ltd)',
  streetAddress: '2nd Floor, 26, 5th Cross, Off Hennur Road, Kacharakanahalli',
  footerAddressHtml:
    'BIOPOWER (BPG Renewables Pvt Ltd)<br>2nd Floor, 26, 5th Cross, Off Hennur Road, Kacharakanahalli,<br>Bengaluru, Karnataka 560084',
  latitude: 13.020937,
  longitude: 77.634512,
  heroImages: {
    biogas: 'images/plants/institutional-biogas-plant.webp',
    owc: 'images/plants/Fully Autoimatic.webp',
    stp: 'images/plants/institutional-biogas-plant.webp',
    cbg: 'images/plants/6cum/Aerial view of green biogas digester.webp',
    hotel: 'images/wonderbin_roof_top.webp',
    apartment: 'images/wonderbin_roof_top.webp',
    college: 'images/plants/institutional-biogas-plant.webp',
    industry: 'images/plants/institutional-biogas-plant.webp',
    food: 'images/plants/Fully Autoimatic.webp',
    resources: 'images/plants/institutional-biogas-plant.webp',
    faq: 'images/biopower-logo.webp',
  },
};
